apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirp
  labels:
    app: chirp
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chirp
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chirp
    spec:
      containers:
        - name: chirp
          image: chirp:latest
          imagePullPolicy: Never # Always, IfNotPresent, Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: chirp-env
            - secretRef:
                name: chirp-env-secret
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          resources: {}