apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: chirp-env-secret
  labels:
    app: chirp
data:
  # echo -n "string" | base64
  # ecto://postgres:postgres@host.docker.internal/chirp_prod
  DATABASE_URL: "ZWN0bzovL3Bvc3RncmVzOnBvc3RncmVzQGhvc3QuZG9ja2VyLmludGVybmFsL2NoaXJwX3Byb2Q="
  ERLANG_COOKIE: "Y29va2ll"
  SECRET_KEY_BASE: "ZnpCazhPRWNJOHRoR3hseXBXUFVxZlIydzJXb3BkTjh2OHBtcHV5MkpOajJlZXJiWUZubGVjdVZNckZQR1luVw=="