apiVersion: v1
kind: Service
metadata:
  name: chirp
  labels:
    app: chirp
spec:
  type: LoadBalancer # LoadBalancer, NodePort, ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: chirp